// Generates/refreshes lib/writing/contentIds.ts, the committed sidecar that
// pairs every lib/writing/contentRegistry.ts pool entry with a stable,
// text-edit-proof id. Read-only over the generation source; writes only the
// sidecar. Never imported at runtime — the app reads the committed
// contentIds.ts directly (see lib/writing/contentRegistry.ts).
//
// Usage: bun scripts/genContentIds.ts
//
// --- Id shapes ---------------------------------------------------------------
//
// Ordinal pools (plain string[] entries — the overwhelming majority):
//   `${poolId}~${ordinal}`, ordinal = the entry's array index the FIRST time
//   this script ever saw it.
//
// Keyed pools (traits.western / traits.chinese / traits.mbti): these three
// pools are the one spot contentRegistry.ts flattens a whole
// Record<string,string> into one pool's entries via Object.entries(...) —
// array position there is just Object.entries' enumeration order, not a
// durable identity the way an authored array's position is. So these use
// `${poolId}~${key}` instead, e.g. "traits.western~Aries" — the dictionary
// key IS the stable identity, immune to the table gaining/losing entries
// elsewhere in the object.
//
// --- Re-run behavior (ordinal pools) -----------------------------------------
//
// Every existing index keeps its existing id, whatever text now sits there —
// an in-place text edit does NOT change the id (that's the whole point of the
// hybrid-id decision; see wiki/notes/decision-sketch-tensor-field.md's sibling
// decision notes for the writing-lab spine). Only indices past the previous
// run's length are "genuinely new" and mint fresh ordinals, continuing after
// the highest ordinal any id in this pool has used historically (so a pool
// that shrank and regrew — not a sanctioned workflow, see below — can't
// silently reuse a retired id and misattribute an old override to new text).
//
// This script does NOT attempt reorder or cut detection beyond straight
// positional preservation: labStore.ts's guarded exporter (lib/writing/
// labStore.ts) blocks anything that would reorder, cut, or add entries from
// ever reaching the source files in the first place, so a legitimately-
// shipped source array only ever grows or gets in-place text edits. A source
// array hand-edited outside that tool (splicing/reordering entries directly
// in lib/seed/*.ts) is already a determinism footgun on its own terms — this
// script won't crash on it, but it will not reverse-engineer which old id an
// entry "really" is if it moved.
//
// --- Baseline note ------------------------------------------------------------
//
// The very first run (no previous contentIds.ts data for a pool) mints ids in
// pure array order — `poolId~0`, `poolId~1`, ... — which is exactly the
// index→id map labStore.ts's v1→v2 migration needs to translate existing
// (poolId, index)-keyed localStorage into (poolId, entryId) keys.

import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildContentRegistry } from "../lib/writing/contentRegistry";
import { CONTENT_IDS as PREVIOUS_IDS } from "../lib/writing/contentIds";
import {
  WESTERN_SIGN_TRAITS,
  CHINESE_ANIMAL_TRAITS,
  MBTI_DESCRIPTIONS,
} from "../lib/seed/personaData";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.resolve(SCRIPT_DIR, "../lib/writing/contentIds.ts");

// Pools flattened from a Record by contentRegistry.ts — id = dict key, not
// array position (see header). If a new keyed-dictionary pool shows up later,
// add it here.
const KEYED_POOLS: Record<string, Record<string, string>> = {
  "traits.western": WESTERN_SIGN_TRAITS,
  "traits.chinese": CHINESE_ANIMAL_TRAITS,
  "traits.mbti": MBTI_DESCRIPTIONS,
};

function parseOrdinal(id: string): number {
  const m = /~(\d+)$/.exec(id);
  return m ? Number(m[1]) : -1;
}

function refreshOrdinalPool(poolId: string, length: number, oldIds: string[]): string[] {
  const ids: string[] = [];
  let nextOrdinal = 1 + oldIds.reduce((max, id) => Math.max(max, parseOrdinal(id)), -1);
  for (let i = 0; i < length; i++) {
    if (i < oldIds.length) {
      ids.push(oldIds[i]); // preserved verbatim — text may have changed, id doesn't
    } else {
      ids.push(`${poolId}~${nextOrdinal}`);
      nextOrdinal++;
    }
  }
  return ids;
}

function refreshKeyedPool(poolId: string, record: Record<string, string>): string[] {
  return Object.keys(record).map((key) => `${poolId}~${key}`);
}

function formatModule(ids: Record<string, string[]>): string {
  const lines: string[] = [
    "// GENERATED by scripts/genContentIds.ts — do not hand-edit; re-run the",
    "// script to refresh. Stable content ids: CONTENT_IDS[poolId][index]",
    "// identifies one entry in lib/writing/contentRegistry.ts's pool of the",
    "// same id (index-aligned with that pool's `entries` array). Ordinal pools",
    '// use `${poolId}~${ordinal}`; the three trait pools (flattened from a',
    '// keyed Record by the registry) use `${poolId}~${key}` instead — see the',
    "// generator's header comment (scripts/genContentIds.ts) for why.",
    "",
    "export type PoolId = string;",
    "",
    "export const CONTENT_IDS: Record<PoolId, string[]> = {",
  ];
  for (const poolId of Object.keys(ids).sort()) {
    lines.push(`  ${JSON.stringify(poolId)}: ${JSON.stringify(ids[poolId])},`);
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

function main() {
  const pools = buildContentRegistry();

  const next: Record<string, string[]> = {};
  let newPools = 0;
  let newEntries = 0;

  for (const pool of pools) {
    const keyed = KEYED_POOLS[pool.id];
    const oldIds = PREVIOUS_IDS[pool.id] ?? [];
    if (!(pool.id in PREVIOUS_IDS)) newPools++;

    const ids = keyed
      ? refreshKeyedPool(pool.id, keyed)
      : refreshOrdinalPool(pool.id, pool.entries.length, oldIds);

    if (ids.length !== pool.entries.length) {
      console.error(
        `FATAL: ${pool.id} produced ${ids.length} ids for ${pool.entries.length} entries — refusing to write a mismatched sidecar.`,
      );
      process.exit(1);
    }
    newEntries += Math.max(0, ids.length - oldIds.length);
    next[pool.id] = ids;
  }

  const droppedPools = Object.keys(PREVIOUS_IDS).filter((id) => !(id in next));
  const totalEntries = Object.values(next).reduce((n, a) => n + a.length, 0);

  writeFileSync(OUT_PATH, formatModule(next), "utf8");

  console.log(`wrote ${path.relative(process.cwd(), OUT_PATH)}`);
  console.log(`  ${pools.length} pools, ${totalEntries} entries`);
  if (newPools > 0) console.log(`  ${newPools} new pool(s)`);
  if (newEntries > 0) console.log(`  ${newEntries} new entr${newEntries === 1 ? "y" : "ies"} minted fresh ids`);
  if (droppedPools.length > 0) console.log(`  dropped pool(s) no longer in the registry: ${droppedPools.join(", ")}`);
}

main();
